title: Nostr Files
description: Всё, что нужно знать о Nostr
theme: just-the-docs

url: https://github.com/bitcoin21ideas/nostr-files

aux_links:
  Nostr Files on GitHub: https://github.com/bitcoin21ideas/nostr-files
  
  
# Back to top link
back_to_top: true
back_to_top_text: "Наверх"

footer_content: "nostr-файлы -- это некоммерческий образовательный проект, который нуждается в поддержке сообщества.

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false
