title: Nostr Files
description: Всё, что нужно знать о Nostr
theme: just-the-docs

url: https://github.com/bitcoin21ideas/nostr-files

aux_links:
  Nostr Files on GitHub: https://github.com/bitcoin21ideas/nostr-files
  
  

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/_images/nostr-files logo.png"



