title: Nostr Files
description: Всё, что нужно знать о Nostr
theme: just-the-docs

url: https://github.com/bitcoin21ideas/nostr-files

aux_links:
  Nostr Files on GitHub: https://github.com/bitcoin21ideas/nostr-files

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/nostr-files logo.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/Nostr_Files_favicon.ico"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

callouts:
 warning:
  title: Внимание!
  color: yellow

callouts:
 info:
  title: Справка
  color: purple

callouts:
  quote:
   title: Цитата
   color: grey-lt


   

